In [4]:
import pandas as pd 
import numpy as np
import seaborn as sns
import os
import matplotlib.pyplot as plt
import joblib

plt.style.use("fivethirtyeight")

In [51]:
class Perceptron:
    def __init__(self,eta:float=None,epochs:int=None):
        self.weights=np.random.randn(3)*1e-4 #small random weights
        trainings= eta is not None and epochs is not None
        if trainings:
            print(f"initial weight before training is-->{self.weights}")
        self.eta=eta
        self.epochs=epochs

    def _z_outcome(self,inputs,weights):
        return np.dot(inputs,weights)
    
    def activation_function(self,z):
        return np.where(z >0 ,1,0)
    
    def fit(self,X,y):
        self.x=X
        self.y=y
        x_with_bias=np.c_[self.x,-np.ones((len(self.x),1))]
        print(f"x with bias: {x_with_bias}")
        
        for epoch in range(self.epochs):
            print(f"for epoch >> {epoch+1}")
            z=self._z_outcome(x_with_bias,self.weights)
            y_hat=self.activation_function(z)
            print(f"Predicted value after forward pass: {y_hat}")
            self.error=self.y-y_hat
            print(f"error: {self.error}")
            self.weights=self.weights+self.eta*np.dot(x_with_bias.T,self.error)
            print(f"Updated weights after epoch: {epoch}/{self.epochs}: \n{self.weights} ")
    
    def predict(self,test_inputs):
        x_with_bias=np.c_[self.x,-np.ones((len(test_inputs),1))]
        z=self._z_outcome(x_with_bias,self.weights)
        return self.activation_function
    
    def loss(self):
        total_loss=np.sum(self.error)
        print(f"Total loss: {total_loss}\n")
        return total_loss
    
    def _create_dir_return_path(self,model_dir,filename):
        os.makedirs(model_dir,exist_ok=True)
        return os.path.join(model_dir,filename)
    
    def save(self,filename,model_dir):
        if model_dir is not None:
            model_file_path=self._create_dir_return_path(model_dir,filename)
            joblib.dump(self,model_file_path)
        else:
            model_file_path=self._create_dir_return_path("model",filename)
            joblib.dump(self,model_file_path)
            
    def load(self,file_path):
        return joblib.load(file_path)
    

In [52]:
def prepare_data(df,target):
    x=df.drop(target,axis=1)
    y=df[target]
    return x,y

In [53]:
AND_GATE={
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,0,0,1]
}
df=pd.DataFrame(AND_GATE)

In [54]:
df.head()

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [55]:
X,y=prepare_data(df,"y")

In [56]:
eta=0.001 
epochs=10

model_and=Perceptron(eta=eta,epochs=epochs)
model_and.fit(X,y)
_=model_and.loss()

initial weight before training is-->[ 7.91566346e-08 -5.14884142e-05 -4.71187147e-05]
x with bias: [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch >> 1
Predicted value after forward pass: [1 0 1 0]
error: 0   -1
1    0
2   -1
3    1
Name: y, dtype: int64
Updated weights after epoch: 0/10: 
[7.91566346e-08 9.48511586e-04 9.52881285e-04] 
for epoch >> 2
Predicted value after forward pass: [0 0 0 0]
error: 0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights after epoch: 1/10: 
[ 1.00007916e-03  1.94851159e-03 -4.71187147e-05] 
for epoch >> 3
Predicted value after forward pass: [1 1 1 1]
error: 0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weights after epoch: 2/10: 
[7.91566346e-08 9.48511586e-04 2.95288129e-03] 
for epoch >> 4
Predicted value after forward pass: [0 0 0 0]
error: 0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights after epoch: 3/10: 
[0.00100008 0.00194851 0.00195288] 
for epoch >> 5
Predicted value after forw